DROP DATABASE IF EXISTS Hotel_System;
CREATE DATABASE IF NOT EXISTS Hotel_System;
USE Hotel_System;

CREATE TABLE `Users`(
	`ID` INT NOT NULL,
	`FirstName` VARCHAR(15) NOT NULL,
	`SurName` VARCHAR(15) NOT NULL,
	`Address` VARCHAR(15) NOT NULL,
	`PostCode` VARCHAR(6) NOT NULL,
	`Mobile` VARCHAR(13) NOT NULL,
	`Email` VARCHAR(45) NOT NULL,
	`Nationality` VARCHAR(25) NOT NULL,
    `DateOfBirth` DATE NOT NULL,
    `Gender` VARCHAR(7) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE `Admins`(
	`AdminID` INT NOT NULL,
	`AdminName` VARCHAR(40) NOT NULL,
    `Password` CHAR(8) NOT NULL
);

CREATE TABLE `Hotel`(
	`AdminID` INT NOT NULL,
	`HID` INT NOT NULL,
    `ID` INT NOT NULL,
    `Prove` VARCHAR(15) NOT NULL,
    `DateIn` DATE NOT NULL,
    `DateOut` DATE NOT NULL,
    `Meal` VARCHAR(45) NOT NULL,
    `RmType` VARCHAR(15) NOT NULL,
    `RmNo` INT NOT NULL,
    FOREIGN KEY(ID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(AdminID) REFERENCES Admins(AdminID) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY(HID)
);

